package br.unesc.reserva.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class JanelaPrincipal extends javax.swing.JFrame {
   
    JanelaPrincipal jp = new JanelaPrincipal();
    JanelaSala js = new JanelaSala();
    
    public JanelaPrincipal() {
     
        
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        itemMenuSobre.addActionListener(new ActionListener() {            
            public void actionPerformed(ActionEvent ae) {
                JOptionPane.showMessageDialog(null, "Reserva v1.0", "Sobre", JOptionPane.INFORMATION_MESSAGE);
            }
        });
        
        itemMenuReserva.addActionListener(new ActionListener() {            
            public void actionPerformed(ActionEvent ae) {
                // Aqui abre a reserva
            }
        });
        
        itemMenuSala.addActionListener(new ActionListener() {            
            public void actionPerformed(ActionEvent ae) {
                // Aqui abre a sala                
                jp.add(js);
                js.setVisible(true);
                
            }
        });
        
        itemMenuResponsavel.addActionListener(new ActionListener() {            
            public void actionPerformed(ActionEvent ae) {
                // Aqui abre o responsável
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        itemMenuReserva = new javax.swing.JMenuItem();
        itemMenuSala = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        itemMenuResponsavel = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        itemMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painelFundo.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuCadastros.setText("Cadastros");

        itemMenuReserva.setText("Reserva");
        menuCadastros.add(itemMenuReserva);

        itemMenuSala.setText("Sala");
        menuCadastros.add(itemMenuSala);

        itemMenuResponsavel.setText("Responsável");
        menuCadastros.add(itemMenuResponsavel);
        
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
              System.exit(0);
              
            }
        });
        menuCadastros.add(itemSair);
        
        menuBar.add(menuCadastros);

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
              
        itemMenuSobre.setText("Sobre");
        menuSobre.add(itemMenuSobre);

        menuBar.add(menuSobre);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        
    }//GEN-LAST:event_menuSobreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuReserva;
    private javax.swing.JMenuItem itemMenuResponsavel;
    private javax.swing.JMenuItem itemMenuSala;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JMenuItem itemSair;
    
    private javax.swing.JMenuBar menuBar;
    
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuSobre;
    
    private javax.swing.JPanel painelFundo;
    // End of variables declaration//GEN-END:variables
}
